import { cn } from "@/lib/utils";
import Providers from "@/providers";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn([
          GeistSans.variable,
          GeistMono.variable,
          "antialiased font-sans",
        ])}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
