name: Deploy NextJS App with AWS EC2 CI/CD

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "${SSH_KEY}" > ssh_key.pem
          chmod 600 ssh_key.pem
          scp -i ssh_key.pem -o StrictHostKeyChecking=no -r ./* ubuntu@${EC2_IP}:~/app
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${EC2_IP} \
            "source ~/.nvm/nvm.sh && nvm use node && cd ~/app && npm install && bash ~/scripts/deploy.sh ${BRANCH_NAME}"
      - name: Cleanup
        run: |
          rm -f ssh_key.pem
